# environment.yml
name: euclid-agn
channels:
  - astrorama
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - astropy
  - astroquery>=4.10.0
  - ipykernel
  - numpy
  - pandas
  - pip
  - pyvo
